spring:
  datasource:
    url: jdbc:mysql://localhost:13306/ticket
    username: ticket
    password: ticket
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
